### ISSUE TITLE
Wrong base URI string is calculated when the provided URI contains url-encoded characters

### ISSUE THREAD

**Issue by ech0s7r** [Mastercard/oauth1-signer-java#18]
According to https://tools.ietf.org/html/rfc5849#section-3.4.1.2:

The HTTP request:

     GET /r%20v/X?id=123 HTTP/1.1
     Host: EXAMPLE.COM:80

is represented by the base string URI: "http://example.com/r%20v/X" and not "http://example.com/r%2520v/X" as currently computed from the lib.

See also: https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/test/java/com/mastercard/developer/oauth/OAuthTest.java#L207-L210

---

### A failing example:
1. Client want to make this request: https://example.com/api/foo@bar integrating the lib with an  OpenAPI Generated API Client
2. The call builder (in OpenAPI generated client) encode the URL, calling `URLEncoder.encode()`. Since '@' is a reserved character as per [RFC 3986](https://tools.ietf.org/html/rfc3986#page-12), the URL will be encoded to https://example.com/api/foo%40bar
3. The OAuth1.0a lib [normalize](https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/main/java/com/mastercard/developer/oauth/OAuth.java#L208) the URL as per https://tools.ietf.org/html/rfc5849#section-3.4.1.2

**Expected behaviour:**

4a. The normalized base URI string should be: https://example.com/api/foo%40bar

**Actual behaviour:**

4b. The normalized base URI string calculated in the below method is: https://example.com/api/foo%2540bar
https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/main/java/com/mastercard/developer/oauth/OAuth.java#L208

---
#### How some of the other libs are calculating the base URI string:
- NodeJS: https://github.com/Mastercard/oauth1-signer-nodejs/blob/5fa71ac7c0f3570b6ddf9bb947076d508b1111c6/src/OAuth.js#L117-L122
- C#: https://github.com/Mastercard/oauth1-signer-csharp/blob/d00a741414a2d5066d71cf12cb4c28e7de61d4a2/Mastercard.Developer.OAuth1Signer.Core/OAuth.cs#L163
- Ruby: https://github.com/Mastercard/oauth1-signer-ruby/blob/698341b9ba625141e2d20fc2c5225cb28898f6f6/lib/oauth.rb#L118-L121

**Comment by kkrauth** [comment]
Getting URLencoding consistent between the URL, Authorization header and SBS is one of the reasons that these libraries were written in the first place. Differences with URLencoding are the biggest source of issues with getting OAuth1 signatures correct. The URLencoding behavior has been tweaked and tuned endlessly to get it into stable state across all libraries. Therefore, unless the gateway rejects requests containing these special characters in the current implementation, changing this behavior would be inadvisable.

**Comment by ech0s7r** [comment]
Yes, unfortunately, these requests are being rejected from the gateway.

A failing example (rejected from the gateway):
```java
client.setBasePath("https://api.com/api");
Api api = new Api(client); // client is using OkHttpOAuth1Interceptor to sign the requests
String pathParam = "foo@bar";
Response response = api.getResource(pathParam); // the generated getResource() method internally escape the path parameter to 'foo%40bar'
```

- The base URI string computed from the signer lib: `/api/foo%2540bar`

- The Signature Base String: ... `foo%252540bar` ...

The request made:
```
GET /api/foo%40bar HTTP/1.1
Host: api.com
```
**Signature Base String (computed from the lib)**: 
GET&https%3A%2F%2Fapi.com%2Fapi%2Ffoo%252540bar *(omitted the not relevant part)*
**Acceptable signature base string (from the gateway)**: GET&https%3A%2F%2Fapi.com%2Fapi%2Ffoo%2540bar *(omitted the not relevant part)*



The current Java `getBaseUriString` implementation creates a new URI object with the provided schema, authority, and path. If the path contains characters previously encoded, they will be escaped in the new URI object created (the URI internally quote/escape the characters that are not permitted).

https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/main/java/com/mastercard/developer/oauth/OAuth.java#L227-L232

This `GetBaseUriString` behavior is not consistent across all the libraries (c# and nodejs examples, below):

### C# ###
```c#
Assert.AreEqual("http://example.com/r%20v/X", OAuth.GetBaseUriString("http://EXAMPLE.COM/r%20v/X?id=123")); // True
```

### NodeJS ###
```javascript
const baseUri = getBaseUriString("http://EXAMPLE.COM/r%20v/X?id=123");
assert.equal(baseUri, "http://example.com/r%20v/X"); // true
```

### Java ### 
```java
uri = URI.create("http://EXAMPLE.COM/r%20v/X?id=123");
baseUri = OAuth.getBaseUriString(uri);
assertEquals("http://example.com/r%20v/X", baseUri); // false
```

The assertion below is `true`:
https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/test/java/com/mastercard/developer/oauth/OAuthTest.java#L207-L210

**Comment by ech0s7r** [comment]
Yes, unfortunately, these requests are being rejected from the gateway.

A failing example (rejected from the gateway):
```java
client.setBasePath("https://api.com/api");
Api api = new Api(client); // client is using OkHttpOAuth1Interceptor to sign the requests
String pathParam = "foo@bar";
Response response = api.getResource(pathParam); // the generated getResource() method internally escape the path parameter to 'foo%40bar'
```

- The base URI string computed from the signer lib: `/api/foo%2540bar`

- The Signature Base String: ... `foo%252540bar` ...

The request made:
```
GET /api/foo%40bar HTTP/1.1
Host: api.com
```
**Signature Base String (computed from the lib)**: 
GET&https%3A%2F%2Fapi.com%2Fapi%2Ffoo%252540bar *(omitted the not relevant part)*
**Acceptable signature base string (from the gateway)**: GET&https%3A%2F%2Fapi.com%2Fapi%2Ffoo%2540bar *(omitted the not relevant part)*



The current Java `getBaseUriString` implementation creates a new URI object with the provided schema, authority, and path. If the path contains characters previously encoded, they will be escaped in the new URI object created (the URI internally quote/escape the characters that are not permitted).

https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/main/java/com/mastercard/developer/oauth/OAuth.java#L227-L232


The `GetBaseUriString` behavior for some of the other libraries:
### C# ###
```c#
Assert.AreEqual("http://example.com/r%20v/X", OAuth.GetBaseUriString("http://EXAMPLE.COM/r%20v/X?id=123")); // True
```

### NodeJS ###
```javascript
const baseUri = getBaseUriString("http://EXAMPLE.COM/r%20v/X?id=123");
assert.equal(baseUri, "http://example.com/r%20v/X"); // true
```

### Java ### 
```java
uri = URI.create("http://EXAMPLE.COM/r%20v/X?id=123");
baseUri = OAuth.getBaseUriString(uri);
assertEquals("http://example.com/r%20v/X", baseUri); // false
```

The assertion below is `true`:
https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/test/java/com/mastercard/developer/oauth/OAuthTest.java#L207-L210

**Comment by kkrauth** [comment]
Keep in mind that the order in which the SBS and the HTTP request are generated could also influence this. For example, if you pass "raw" unencoded parameters into the OAuth signer library, it will encode them once. However if you construct some kind of a URL object using an arbitrary HTTP library, it might or might not URLencode parameters when you create that object. Passing it to the OAuth1 signer at this point will double encode it.

**Comment by ech0s7r** [comment]
Summing up what is happening with Java oauth1-signer lib v.*1.3.0*, the following request is getting **rejected** from the gateway:

```
GET /api/example/service/test%40api HTTP/1.1
Host: api.mastercard.com
```
- **SBS**:
GET&https%3A%2F%2Fapi.mastercard.com%2Fapi%2Fexample%2Fservice%2Ftest%252540api

- *OAuth signatures did not match. Acceptable signature base string:*
GET&https%3A%2F%2Fapi.mastercard.com%2Fapi%2Fexample%2Fservice%2Ftest%2540api ...

**Note**: the encoded symbol is in the path, not in the query string.

Below, what is currently happening in the signing process for paths with encoded symbols in it (eg. %40):
1. the path is first [encoded](https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/main/java/com/mastercard/developer/oauth/OAuth.java#L229) in the URI() class: %40 is encoded to %2540
2. the path is encoded [again](https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/main/java/com/mastercard/developer/oauth/OAuth.java#L87) in computing the signature base string:  %2540 is encoded to %252540
- The encoded symbol in the HTTP request, remains: %40:
```
GET /api/example/service/test%40api HTTP/1.1
```


The same request, if signed with NodeJS lib, is accepted from the gateway as the SBS computed in that case will be: GET&https%3A%2F%2Fapi.mastercard.com%2Fapi%2Fexample%2Fservice%2Ftest%2540api

The proposed is to don't rely on the URI class for returning the base URI string as it internally quote the characters that are not permitted in the base uri, including path parameters already encoded and making it consistent with the NodeJS implementation.
The base URI is encoded (again) in the `getSignatureBaseString()`
https://github.com/Mastercard/oauth1-signer-java/blob/54e15c4b0ff3f06a26dead18bb554848bcccaf58/src/main/java/com/mastercard/developer/oauth/OAuth.java#L87


The change will not affect the query strings encoding logic, as they are not considered in the `getBaseUriString` and processed separately.
