### ISSUE TITLE
Support for OAuth 2.0 protocol

### ISSUE THREAD

**Issue by aymanapatel** [Mastercard/oauth1-signer-java#23]
Is there another repo or timeline as to when there would be a library that would support OAuth 2.0 protocol?

**Comment by jaaufauvre** [comment]
Hi @aymanapatel,

Thanks for your question!

Mastercard [oauth1-signer projects](https://github.com/Mastercard?q=oauth1-signer-&type=public&language=) are about OAuth 1.0a. They can be used to consume APIs available on the [Mastercard Developer Portal](https://developer.mastercard.com/).

See also: [Using OAuth 1.0a to Access Mastercard APIs](https://developer.mastercard.com/platform/documentation/security-and-authentication/using-oauth-1a-to-access-mastercard-apis/).

What requires you to use the OAuth 2.0 framework? Can you give a bit of context? 

Thanks,

**Comment by jaaufauvre** [comment]
@aymanapatel,

I'm closing this issue as the question is not directly related to this repository. 

Do not hesitate to reach out to the support team as per the options listed here: https://developer.mastercard.com/support/

Thanks,
