### ISSUE TITLE
Update to Java7

### ISSUE THREAD

**Issue by kkrauth** [Mastercard/oauth1-signer-java#3]
Since the Mastercard API gateway requires TLS 1.2 as minimum which is not supported by Java6 out of the box, there is no point maintaining 1.6 compatibility.

**Comment by jaaufauvre** [comment]
Hi Kosta,

It should be OK. Let me know if you see something else that needs to be changed.

J.-A.

**Comment by kkrauth** [comment]
Was hoping we could take advantage of some of the syntax sugar that 1.7 introduces too. Like diamond operators for assignments of generics.

**Comment by jaaufauvre** [comment]
I missed that indeed. Done!

**Comment by kkrauth** [comment]
👍 Thanks!
