### ISSUE TITLE
[BUG] Oauth Body Hash generated is not matching when the payload has a forward slash

### ISSUE THREAD

**Issue by vidhya2192** [Mastercard/oauth1-signer-java#33]
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
If any attributes of the request payload has a forward slash ,the body hash generated is different and the actual call to master card consumer clarity API is failing with error incorrect body hash 

**To Reproduce**
Use a payload with forward slash in any of request attributes , and verify getAuthorizationHeader method

**Expected behavior**
Oauth body hash should be correct 

**Screenshots**

**Additional context**
Add any other context about the problem here (OS, language version, etc..).

**Related issues/PRs**
Has a similar issue/PR been reported/opened before? No

**Suggest a fix/enhancement**
If you can't fix the bug yourself, perhaps you can point to what might be causing the problem (line of code or commit), or simply make a suggestion.

**Comment by joseph-neeraj** [comment]
Hi @vidhya2192 , please fill in the details in the issue template so we can better understand the problem.

**Comment by ShimonaR-MC** [comment]
Hi @vidhya2192, we are closing the issue due to inactivity. Please feel free to reopen the issue when you have sufficient information.
